### ISSUE TITLE
A more usable Sense Output

### ISSUE THREAD

**Issue by cotiso** [nodtvedt/qlik-sense-r-regression-extension#1]
Hi nodtvedt,

Great example ! Thank you for all the trouble.

In order to make this more useful in Sense interface, it would be cool to have the result in Sense displayed not as the regular text R is returning, but as a table with 5 columns:

Call                                       Intercept           mkt_tf           smb             hml
Im(formula = ....)                   -0.0013338      -0.8139       0.5896         0.612605

(for your example)

**Comment by nodtvedt** [comment]
Thanks for the feedback.

Indeed, I agree it would be useful to provide a prettier formatting of the result set. It is not trivial to parse the text result from lm() and convert it to a table though, and my initial experiments leads me to believe I'd be better off if I write an R wrapper on the server that returns the result set as a JSON object rather than faffing about with string-parsing.

I'm unlikely to spend time on modifying this proof-of-concept, but I'd be happy to merge any contributed code you may have.

**Comment by cotiso** [comment]
Tx for the fast answer.

Not yet such an advanced R develeoper… I would rather try in Qlik some things…

In case we do something relevant, I will let you know.

Tx again for making the sample and sharing.

Sempre fi,

Cotiso
